name: infra-pipeline
trigger:
  - master
  
variables:
  ARM_SUBSCRIPTION_ID: $(azsubscriptionid) 
  tfbinaryurl: 'https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip'

pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  jobs:
  - job: 
    steps:
    - task: AzureCLI@2
      displayName: 'get terraform'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'wget $(tfbinaryurl) -O terraform.zip && unzip terraform.zip && chmod +x ./terraform && sudo mv ./terraform /usr/local/bin/'
        useGlobalConfig: true
        addSpnToEnvironment: true    
      
    - task: AzureCLI@2
      displayName: 'terraform init'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          terraform init
        useGlobalConfig: true
        addSpnToEnvironment: true
      
    - task: AzureCLI@2
      displayName: 'terraform format check'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform fmt -check'
        useGlobalConfig: true
        addSpnToEnvironment: true
      
    - task: AzureCLI@2
      displayName: 'terraform validate'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform validate'
        useGlobalConfig: true
        addSpnToEnvironment: true
      
    - task: AzureCLI@2
      displayName: 'terraform lint'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'docker run --rm -v $(pwd):/data -t wata727/tflint'
        useGlobalConfig: true
        addSpnToEnvironment: true
      
    - task: AzureCLI@2
      displayName: 'terraform plan'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform plan -out plan.tfplan'
        useGlobalConfig: true
        addSpnToEnvironment: true
        
- stage: Deploy
  jobs:
  - job: 
    steps:
    - task: AzureCLI@2
      displayName: 'get terraform'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'wget $(tfbinaryurl) -O terraform.zip && unzip terraform.zip && chmod +x ./terraform && sudo mv ./terraform /usr/local/bin/'
        useGlobalConfig: true
        addSpnToEnvironment: true 
    
    - task: AzureCLI@2
      displayName: 'terraform init'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform init'
        useGlobalConfig: true
        addSpnToEnvironment: true
  
    - task: AzureCLI@2
      displayName: 'terraform destroy'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform destroy -auto-approve -no-color'
        useGlobalConfig: true
        addSpnToEnvironment: true

    - task: AzureCLI@2
      displayName: 'terraform plan'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform plan -out plan.tfplan'
        useGlobalConfig: true
        addSpnToEnvironment: true

    - task: AzureCLI@2
      displayName: 'terraform apply'
      inputs:
        azureSubscription: '$(azserviceconnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform apply -auto-approve -no-color plan.tfplan'
        useGlobalConfig: true
        addSpnToEnvironment: true
