# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
 batch: true
  
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.13.0'

- task: TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: '$(azsubscription)'
    backendAzureRmResourceGroupName: 'tf-template'
    backendAzureRmStorageAccountName: 'tf-template'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf-template.terraform.tfstate'

- task: TerraformCLI@0
  displayName: 'terraform validate'
  inputs:
    command: 'validate'
    backendType: 'azurerm'
    backendServiceArm: '$(azsubscription)'
    backendAzureRmResourceGroupName: 'tf-template'
    backendAzureRmStorageAccountName: 'tf-template'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf-template.terraform.tfstate'

- task: AzureCLI@2
  displayName: 'terraform lint'
  inputs:
    azureSubscription: '$(azsubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'docker run --rm -v $(pwd):/data -t wata727/tflint'